clone_folder: C:\ssl-vision
shallow_clone: true

environment:
  global:
    MSYS_DIR: C:\msys64
    QT_MinGW_DIR: C:\Qt\5.11.2\mingw53_32
  matrix:
    - platform: x86
      platform_name: i686
      bit: 32
    - platform: x64
      platform_name: x86_64
      bit: 64 
        

init:
  - set PATH=%MSYS_DIR%\usr\bin
  - IF %bit% EQU 64 
    pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-qt5
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-protobuf
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-eigen3
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-cmake
  - pacman --noconfirm -Su mingw%bit%/mingw-w64-%platform_name%-opencv
  
build_script:
  - set PATH=%MSYS_DIR%\mingw%bit%\bin;%QT_MinGW_DIR%\bin
  - mkdir C:\build_mingw_%platform%
  - cd C:\build_mingw_%platform%
  - cmake.exe -G "MinGW Makefiles" C:\ssl-vision
  - cmake.exe --build . -j 4